### PR TITLE
Require Jenkins 2.440.3 or newer

### PR DESCRIPTION
**Pull request by strangelookingnerd**
### Require Jenkins 2.440.3 or newer

55% of the installations of the most recent release (4.4) are running 2.440.3 or newer as noted by [plugin installation statistics](https://stats.jenkins.io/pluginversions/plasticscm-plugin.html)

Jenkins  2.440.3 includes a fix for a critical security vulnerability. Users should upgrade to 2.440.3 or newer in order to have that critical fix.

### Testing done
Verified changes using `mvn clean verify`

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by strangelookingnerd** [comment]
The checks fail as the proposed changes will require minimum Java 11 - I updated the `Jenkinsfile` as well.

**Comment by mig42** [comment]
Hi @strangelookingnerd , thanks for the PR. I'm leaning towards merging it, but could you please explain a little bit more about the build error? Why isn't it enough to update the Jenkinsfile in this PR? I'd like to avoid merging PRs with errors unless there isn't a better option.

**Comment by strangelookingnerd** [comment]
> Hi @strangelookingnerd , thanks for the PR. I'm leaning towards merging it, but could you please explain a little bit more about the build error? Why isn't it enough to update the Jenkinsfile in this PR? I'd like to avoid merging PRs with errors unless there isn't a better option.

It’s a security measure by ci.jenkins.io to not use the updated Jenkinsfile. In the build log for the action you should also see the output for that: 

```

07:26:08  Loading trusted files from base branch master at fedbc1f48fe5f076eae6c2ad984fa3081dd0ce9b rather than 86a1e66f45848541040f2a5806d638acb31a3d57
07:26:08  Obtained Jenkinsfile from fedbc1f48fe5f076eae6c2ad984fa3081dd0ce9b
07:26:08  ‘Jenkinsfile’ has been modified in an untrusted revision
07:26:08  Loading library pipeline-library@master
07:26:08  Library pipeline-library@master is cached. Copying from home.

```

**Review by mig42 — APPROVED** [review]
LGTM

**Pull request merged**
